sudo: required

dist: trusty

language: cpp

compiler:
  - gcc

os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.7
    - valgrind
    - libcppunit-dev
    - libcppunit-1.13-0
    - build-essential

before_install:
  - pip install --user cpp-coveralls

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - git clone https://github.com/mabseher/htd
  - mkdir build_htd
  - cd build_htd
  - cmake -DBUILD_SHARED_LIBS=True -DHTD_USE_EXTENDED_IDENTIFIERS=True DCMAKE_CXX_FLAGS="${CXX_FLAGS}" ../htd
  - make
  - sudo make install
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
  - cd ..
  - mkdir build_test
  - cd build_test
  - cmake -Dtests=ON ../
  - make
  - cd ..
  - chmod +x ./test_travis.sh
  - ls /usr/local/lib/

script:
  - ./test_travis.sh

after_success:
  - coveralls -b ./build_test/lib_exst/CMakeFiles/lib_exst.dir/src/ --exclude libclasp --exclude htd --exclude tests --gcov-options '\-lp'